id: IDD40D0B1
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 15:21:47.156492+00:00
last_modified: 2022-12-14 15:21:47.156497+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-068-019
  eft-text-version: 1.1.2 2020
  title: Toh_285-The_Dedication_Fulfilling_All_Aspirations-v2
bases:
  5FF7:
    source_metadata: null
    order: 1
    base_file: 5FF7.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
